_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 4
beta:
    value: 0.5
beta1:
    value: 0.5
beta2:
    value: 0.5
dataset:
    value: fashion_mnist
epochs:
    value: 1
epsilon:
    value: 1e-06
hidden_size:
    value: 4
learning_rate:
    value: 0.1
loss:
    value: cross_entropy
momentum:
    value: 0.5
num_layers:
    value: 1
optimizer:
    value: sgd
weight_decay:
    value: 0
weight_init:
    value: random
