wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
hidden_size:
  value: 128
lr:
  value: 0.0001
n_hidden:
  value: 3
num_epochs:
  value: 5
optimizer:
  value: nag
weight_decay:
  value: 0.0005
weights_init:
  value: random
