wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
hidden_size:
  value: 32
lr:
  value: 0.0001
n_hidden:
  value: 3
num_epochs:
  value: 5
optimizer:
  value: nag
weight_decay:
  value: 0.5
weights_init:
  value: xavier
