wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_size:
  value: 128
lr:
  value: 0.0001
n_hidden:
  value: 4
num_epochs:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weights_init:
  value: xavier
