wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
hidden_size:
  value: 128
lr:
  value: 0.001
n_hidden:
  value: 3
num_epochs:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weights_init:
  value: random
