wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
hidden_size:
  value: 128
lr:
  value: 0.0001
n_hidden:
  value: 5
num_epochs:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weights_init:
  value: xavier
