wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value: 32
lr:
  value: 0.001
n_hidden:
  value: 3
num_epochs:
  value: 10
optimizer:
  value: nadam
weight_decay:
  value: 0
weights_init:
  value: random
