wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value: 128
lr:
  value: 0.0001
n_hidden:
  value: 4
num_epochs:
  value: 10
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weights_init:
  value: random
