wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
hidden_size:
  value: 32
lr:
  value: 0.001
n_hidden:
  value: 5
num_epochs:
  value: 10
optimizer:
  value: adam
weight_decay:
  value: 0.5
weights_init:
  value: xavier
